### PR TITLE
feat: disable any mutation on user-defined pages

### LINKED ISSUE #568: feat: disable any mutation on user-defined pages
There may be infinite number of webpages like GitHub’s edit.
configuration pop-up must be more powerful!
The denied list should be supported with a **good default**.

### PR DESCRIPTION
**Pull request by kumachan-mis**
Error handling is remained, but it'll implemented in the next PR

### CODE REVIEW

**Comment by kumachan-mis** [comment]
YAGNI is important!
visualization of any webpage is not actually needed!
Allow and Deny are needless functions

**Comment by kumachan-mis** [comment]
@rdrgn 
This PR still have styling problems. Could you support the following two features?
(Please push to this branch directly) 

1. TextField for multiline text

I apply ad-hoc change to support multiline text. But, better solution would exist...!!

2. ItemContainer not only for horizontal layout but for vertical layout

current layout is like
```
| Denied URLs (label) | foo.com (text) | apply (button) |
```
but I want
```
| Denied URLs (label)     |
foo.com
         | apply (button) |
```

**Review by exKAZUu — APPROVED** [review]
LGTM :+1:

**Pull request merged**
