### PR TITLE
feat: add support for generic pu/puml/plantuml files

### PR DESCRIPTION
**Pull request by nimatrueway**
Remark: for github raw-files `Laboratory by Mozilla` is needed to ease CSP restrictions.

### CODE REVIEW

**Comment by nimatrueway** [comment]
Would you mind releasing the updated version?

**Comment by exKAZUu** [comment]
@nimatrueway Sorry for the delay. We are just waiting for Google’s review.
(The release of the latest version requires thorough review due to the change of `permissions`)

**Comment by exKAZUu** [comment]
FYI: Mozilla accepted our Firefox extension though Google is still reviewing our Chrome extension...

**Comment by exKAZUu** [comment]
I now noticed the Chrome extension had been published on 6th. Thanks!

**Pull request merged**
