### PR TITLE
chore: disable ESLint for SCSS on Svelte

### LINKED ISSUE #576: chore: fix the lint config for SCSS on Svelte
`yarn lint` fails to parse SCSS.

Example
https://github.com/WillBooster/plantuml-visualizer/runs/2258228841

### PR DESCRIPTION
**Pull request by rdrgn**
close #576

### CODE REVIEW

**Comment by exKAZUu** [comment]
Can't we support scss?
FYI: https://github.com/sveltejs/svelte-preprocess

**Comment by kumachan-mis** [comment]
It's not a problem of svelte, but that of eslint.
`svelte` compiler supports scss, but its eslint plugin,`eslint-plugin-svelte3` doesn't

**Review by kumachan-mis — APPROVED** [review]

**Comment by exKAZUu** [comment]
https://github.com/sveltejs/eslint-plugin-svelte3#svelte3ignore-styles
okay, so there is no way to lint non-css style code ...

**Comment by rdrgn** [comment]
If you just lint styles, you can use [Stylelint](https://stylelint.io/).

**Pull request merged**
